### ISSUE TITLE
XDebug not working

### ISSUE THREAD

**Issue by marconett** [LarryEitel/laravel-laradock-phpstorm#4]
Hi Larry,

thank you for the nice write up on how to link LaraDock with PHPStorm. Sadly, I'm not able to get XDebug to work. Running tests works, but setting breakpoints doesn't. If I try to debug, PHPStorm just says: `Connection with 'xdebug 2.4.0.' was not established.`

The command PHPStorm uses is `ssh://root@localhost:2222/usr/bin/php -dzend_extension=/usr/lib/php/20151012/xdebug.so -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=172.18.0.1 /root/.phpstorm_helpers/phpunit.php --configuration /var/www/laravel/phpunit.xml ExampleTest /var/www/laravel/tests/ExampleTest.php`.

If I ssh into the workspace container and use the command manually, it tells me `Cannot find PHPUnit in include path (.:/usr/share/php)` and exits with code 1. But the same also happens when trying the command that is used to run tests, so I don't think that's the problem.
- PHPStorm can successfully connect to the workspace container via SSH (changed port to 2222, but no issue there).
- The host '172.18.0.1' is reachable from inside the workspace container.
- `/usr/lib/php/20151012/xdebug.so` exists
- Port 9000 is reachable and used by PHPStorm

I most likely messed up some setting in PHPStorm, but I can not figure out where the problem is, as I closely followed your screenshots. Do you have an idea what the problem could be?

**Comment by LarryEitel** [comment]
Can you verify [this](https://github.com/LarryEitel/laravel-laradock-phpstorm/blob/master/screenshots/PHPStorm/Settings/LangsPHPPHPUnit.png) setting?

**Comment by marconett** [comment]
Yea, I have 1:1 the same screen.

**Comment by LarryEitel** [comment]
Are you running PHP 7?

**Comment by LarryEitel** [comment]
Also, in docker-compose you have for php-fpm:

```
environment:
    # IMPORTANT: You must have a Remote Interpreter entry matching this name
    - PHP_IDE_CONFIG="serverName=laravel"
```

**Comment by marconett** [comment]
Yes to both.

**Comment by LarryEitel** [comment]
Also, I have noticed that when I work with other LaraDock projects, I need to delete laradock_\* images and rebuild. Don't know why, but that sometimes resolves matters.

**Comment by marconett** [comment]
I also already tried that :/

**Comment by LarryEitel** [comment]
you have laravel mapped to container IP in your hosts file and pingable?

**Comment by LarryEitel** [comment]
On [this](https://github.com/LarryEitel/laravel-laradock-phpstorm/blob/master/screenshots/PHPStorm/Settings/DeploymentConnection.png), click on Mappings and make sure that `Use this server as default` is activated.

**Comment by marconett** [comment]
> you have laravel mapped to container IP in your hosts file and pingable?

i do not, but is that really necessary? i'm using docker for mac, so i don't have access to the docker network from my local machine unless i expose a port.

another question: if php-fpm is running inside the `php-fpm` container, why do we ssh into the `workspace` container and run xdebug there?

does the file https://github.com/LarryEitel/laravel-laradock-phpstorm/blob/master/laradock/php-fpm/xdebug_settings_only.ini really respect the setup using workspace as debugger?

**Comment by LarryEitel** [comment]
I think you need to be able to resolve laravel to docker machine IP. Might
be the same as I have set. I am in a rush on something else. Can't give
full attention now. :(

**Comment by LarryEitel** [comment]
I had issues after upgrading to latest Docker Beta. After I deleted ALL laradock images and rebuilt, it works!!! :( See [readme](https://github.com/LarryEitel/laravel-laradock-phpstorm#InstallCleanHouse).

**Comment by marconett** [comment]
Deleting all containers and images doesn't fix it. I still not exactly get the debugger setup with php itself running in one container and the debugger running in another.

**Comment by LarryEitel** [comment]
Do you have a Skype ID I can reach you at?

**Comment by LarryEitel** [comment]
If so, go to my profile and find my email to send it.

**Comment by marconett** [comment]
I've send you an email.

**Comment by LarryEitel** [comment]
For other Mac users, @marconett is unable to `ssh` into a running container. See: [ip-address-for-xdebug](https://forums.docker.com/t/ip-address-for-xdebug/10460/7). So far, Marco has been unable to resolve this.

**Comment by LarryEitel** [comment]
Greetings @marconett, were you ever able to resolve the issue you are having with Docker-Mac? Did you ever try: https://forums.docker.com/t/ip-address-for-xdebug/10460/7?

**Comment by marconett** [comment]
Hi @LarryEitel, sorry for the late reply. I have not found the time to pursue this issue since we chatted last week. You can close the ticket for now if you'd like. I will probably look into this again at a later point in time and will keep you updated on the issue if you like to.

**Comment by LarryEitel** [comment]
How about I leave this open for now with a view to either hearing back from you OR someone else reading this coming up with a solution/suggestion.

**Comment by XStepien** [comment]
Hello, same for me... PhpStorm give me the same error message "connection with 'xdebug 2.4.0.' was not established"

I maybe don't understand one think -> **dockerhost** is the same Ip as **laravel** in the host file ?

PS : I can use PhpUnit remote test.

**Comment by LarryEitel** [comment]
These docs are being deprecated. Please check out this [PR branch](https://github.com/LarryEitel/laradock/tree/phpstorm-debug).

**Comment by ghost** [comment]
the same problem here and can not resolve with this doc https://github.com/LarryEitel/laradock/tree/phpstorm-debug

**Comment by LarryEitel** [comment]
Hello @pouya-daneshvar-freelands-it, at this point, all that I can suggest is that you review http://laradock.io/guides/#PHPStorm-Debugging. If you continue to have problems, open an issue there. Hope this helps.
